[package]
name = "rspg"
version = "0.1.0"
authors = ["Dan Regan <dan@regan-analytics.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
