version: '3.7'
services: 
  mongo-srdb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - 27017:27017
    volumes:
      - ./srd-data:/data/srd:ro
      - mongodb-data:/data/db

volumes:
  mongodb-data: